/*

a. SELECT * FROM Barang WHERE HARGA_SATUAN > 10000 ORDER BY HARGA_SATUAN ASC;

b. SELECT * Pelanggan WHERE NAMA LIKE '%g%' AND ALAMAT = 'BANDUNG';

c. SELECT t.KODE, t.TANGGAL, p.NAMA AS NAMA_PELANGGAN, b.NAMA AS NAMA_BARANG, t.JUMLAH, 
(b.HARGA * t.JUMLAH_BARANG) AS TOTAL_HARGA
FROM Transaksi t
JOIN Pelanggan p ON t.KODE_PELANGGAN = p.KODE
JOIN Barang b ON t.KODE_BARANG = b.KODE
ORDER BY t.TANGGAL ASC;

d. SELECT p.NAMA AS NAMA_PELANGGAN, COUNT(t.KODE) AS JUMLAH, SUM(t.JUMLAH_BARANG * b.HARGA_SATUAN) AS TOTAL_HARGA
FROM Transaksi t
JOIN Pelanggan p ON t.KODE_PELANGGAN = p.KODE
JOIN Barang b ON t.KODE_BARANG = b.KODE
GROUP BY p.NAMA;




*/